name: Docker Build and Publish

on:
  push:
    branches:
      - main  # Exécute le workflow uniquement pour les pushes sur la branche main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: DOCKER #environment name where secrets are stored

    steps:
      # Checkout du code source
      - name: Checkout code
        uses: actions/checkout@v3

      # Se connecter à Docker Hub
      - name: Log in to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Créer et taguer l'image Docker
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/sysinfo:latest .
      
      # Publier l'image sur Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/sysinfo:latest